apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdo572-final-pvc
  labels:
    username: mdo572
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
