apiVersion: v1
kind: Service
metadata:
  name: mdo572-final-flask-service
  labels:
    username: mdo572
    env: prod
spec:
  type: ClusterIP
  selector:
    app: mdo572-final-flask
  ports:
  - name: flask-port
    port: 5000
    targetPort: 5000
