apiVersion: v1
kind: Service
metadata:
  name: mdo572-final-redis-service
  labels:
    username: mdo572
    env: prod
spec:
  type: ClusterIP
  selector:
    app: mdo572-final-redis
  ports:
  - name: redis-port
    port: 6379
    targetPort: 6379
