apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdo572-hw7-flask
  labels:
    app: mdo572-hw7-flask
    usernmae: mdo572
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdo572-hw7-flask
  template:
    metadata:
      labels:
        app: mdo572-hw7-flask
    spec:
      containers:
        - name: mdo572-hw7-flask
          imagePullPolicy: Always
          image: nowthatsdamp/hw7:1.1
          command: ["python", "api.py"]
          env:
          - name: REDIS_IP
            value: "10.109.72.116"

