version: '3'
services:
    redis:
        image: redis:latest
        container_name: mdo572-redis
        ports:
            - 6404:6379
        volumes: 
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf"]
    web:
        build: .
        container_name: mdo572-web
        ports:
            - 5024:5000
        volumes:
            - ./data/data_file.json:/datafile.json
