apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdo572-test-pvc
  labels:
    username: mdo572
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
