apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdo572-test-flask-deployment
  labels:
    username: mdo572
    env: test
    app: mdo572-test-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      username: mdo572
      env: test
      app: mdo572-test-flask
  template:
    metadata:
      labels:
        username: mdo572
        env: test
        app: mdo572-test-flask
    spec:
      containers:
        - name: mdo572-test-flask
          imagePullPolicy: Always
          image: nowthatsdamp/coe-332-animals:1.2
          env:
          - name: FLASK_APP
            value: "app.py"
          - name: REDIS_IP
            value: "10.109.72.116"
          ports:
          - name: http
            containerPort: 5000
