apiVersion: v1
kind: Service
metadata:
  name: mdo572-test-redis-service
  labels:
    username: mdo572
    env: test
spec:
  type: ClusterIP
  selector:
    app: mdo572-test-redis
  ports:
  - name: mdo572-test-redis
    port: 6379
    targetPort: 6379
